namespace tests

  class BaseTestSuite extends rooibos.BaseTestSuite
    private appController

    protected override function setup()
      'Do something here all your files need
      'like setup the logger, etc
    end function

    protected override function beforeEach()
      'do things here that all your tests need
      'e.g. for a maestro app
      ' m.appController = { "id": "appController" }
      ' mioc.setInstance("appController", m.appController)
    end function

    protected override function afterEach()
      'tidy things up
      'e.g. for a maestro app
      ' mioc.reset()
      ' mioc.clearClassInstances()
      ' if m.global.__mioc <> invalid
      '   m.global.__mioc = invalid
      ' end if

    end function
  end class
end namespace